config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/schroedinger-hat/certo:
      branch: main
      repo: https://github.com/schroedinger-hat/certo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/schroedinger-hat/certo git:
        commands:
        - /usr/bin/env sh .sqa/script.bone_content_bullfrog.sh
        container: qc.acc_claret_polite_vulture
  QC.Doc:
    repos:
      github.com/schroedinger-hat/certo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.teal_jubilant_cheetah.sh
        container: qc.doc_denim_happy_horse
      github.com/schroedinger-hat/certo git:
        commands:
        - /usr/bin/env sh .sqa/script.boysenberry_easygoing_macaw.sh
        container: qc.doc_glaucous_perceptive_octopus
      github.com/schroedinger-hat/certo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pineapple_wondrous_gorilla.sh
        container: qc.doc_poppy_sad_heron
  QC.Lic:
    repos:
      github.com/schroedinger-hat/certo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.arctic_wondrous_lemur.sh
        container: qc.lic_wine_friendly_catfish
  QC.Sty:
    repos:
      github.com/schroedinger-hat/certo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bone_insightful_rattlesnake.sh
        container: qc.sty_lime_confident_bat
      github.com/schroedinger-hat/certo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lime_studious_thrush.sh
        container: qc.sty_gold_organized_roadrunner
  QC.Ver:
    repos:
      github.com/schroedinger-hat/certo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.claret_sympathetic_alligator.sh
        container: qc.ver_sand_delighted_wildcat
timeout: 5400
