config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/schroedinger-hat/certo:
      branch: main
      repo: https://github.com/schroedinger-hat/certo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/schroedinger-hat/certo git:
        commands:
        - /usr/bin/env sh .sqa/script.pine_inspired_gull.sh
        container: qc.acc_strawberry_zealous_nymph
  QC.Doc:
    repos:
      github.com/schroedinger-hat/certo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fog_polite_kingfisher.sh
        container: qc.doc_papaya_enthusiastic_ostrich
      github.com/schroedinger-hat/certo git:
        commands:
        - /usr/bin/env sh .sqa/script.denim_alert_hummingbird.sh
        container: qc.doc_silver_optimistic_porpoise
      github.com/schroedinger-hat/certo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zinnia_perky_crow.sh
        container: qc.doc_pineapple_loving_phoenix
  QC.Lic:
    repos:
      github.com/schroedinger-hat/certo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.reef_scrappy_cougar.sh
        container: qc.lic_currant_bewildered_bat
  QC.Sty:
    repos:
      github.com/schroedinger-hat/certo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clove_friendly_orangutan.sh
        container: qc.sty_rosewater_industrious_starfish
      github.com/schroedinger-hat/certo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tide_tolerant_jaguar.sh
        container: qc.sty_flamingo_lucky_fox
  QC.Ver:
    repos:
      github.com/schroedinger-hat/certo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.rose_rustic_groundhog.sh
        container: qc.ver_ruby_affectionate_condor
timeout: 5400
