config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/schroedinger-hat/certo:
      branch: main
      repo: https://github.com/schroedinger-hat/certo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/schroedinger-hat/certo git:
        commands:
        - /usr/bin/env sh .sqa/script.incarnadine_tough_peacock.sh
        container: qc.acc_indigo_reckless_stork
  QC.Doc:
    repos:
      github.com/schroedinger-hat/certo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cornflower_joyful_wolf.sh
        container: qc.doc_clementine_hardworking_groundhog
      github.com/schroedinger-hat/certo git:
        commands:
        - /usr/bin/env sh .sqa/script.sepia_friendly_dragon.sh
        container: qc.doc_alabaster_ardent_bat
      github.com/schroedinger-hat/certo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunset_decisive_snail.sh
        container: qc.doc_goldenrod_sarcastic_quail
  QC.Lic:
    repos:
      github.com/schroedinger-hat/certo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.navy_forgiving_hamster.sh
        container: qc.lic_wave_industrious_flamingo
  QC.Sty:
    repos:
      github.com/schroedinger-hat/certo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lilac_industrious_mongoose.sh
        container: qc.sty_magenta_empathetic_leopard
      github.com/schroedinger-hat/certo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fern_mature_dolphin.sh
        container: qc.sty_cayenne_vigilant_kraken
  QC.Ver:
    repos:
      github.com/schroedinger-hat/certo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seafoam_observant_impala.sh
        container: qc.ver_bronze_tolerant_porcupine
timeout: 5400
